# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5272/

###

GET http://localhost:5272/games

###

Get http://localhost:5272/games/4

###

POST http://localhost:5272/games
Content-Type: application/json

{
    "name": "Grand Theft Auto 6",
    "genre": "Action/Adventure",
    "price": 109.99,
    "ReleaseDate": "2026-11-19"
}

###

PUT http://localhost:5272/games/4
Content-Type: application/json

{
    "name": "Grand Theft Auto 6",
    "genre": "Open-World/Immersive",
    "price": 109.99,
    "ReleaseDate": "2026-11-19"
}

###

DELETE http://localhost:5272/games/5